default: &default
  adapter: postgresql
  encoding: unicode
  username: palantir
  pool: 5

development:
  <<: *default
  database: palantir_development
test:
  <<: *default
  database: palantir_test
production:
  <<: *default
  database: palantir_production
  password: <%= ENV['PALANTIR_DATABASE_PASSWORD'] %>
