default: &default
  aws_key: 'test_aws_key'
  aws_secret: 'test_aws_secret'
  twitter_consumer_key: 'test_twitter_consumer_key'
  twitter_consumer_secret: 'test_twitter_consumer_secret'
  twitter_access_token: 'test_twitter_access_token'
  twitter_access_token_secret: 'test_twitter_access_token_secret'
  devise_secret_key: 'd60ddfaa1522ee66abe65e5bcc2ced2b435cc84b60f7c23f7d4c22b1c0bc899a582350cf0e1c7ce46191e3747b2b74b4d98d4e2f58b86e71055fc2e2744b1a30'

development:
  <<: *default
  secret_key_base: <%= ENV['DEV_SECRET'] %>

test:
  <<: *default
  secret_key_base: <%= ENV['TEST_SECRET'] %>

production:
  <<: *default
  secret_key_base: <%= ENV['PROD_SECRET'] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  twitter_access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  twitter_access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
