default: &default
  aws_key: 'test_aws_key'
  aws_secret: 'test_aws_secret'
  twitter_consumer_key: 'test_twitter_consumer_key'
  twitter_consumer_secret: 'test_twitter_consumer_secret'
  twitter_access_token: 'test_twitter_access_token'
  twitter_access_token_secret: 'test_twitter_access_token_secret'
  devise_secret_key: 'd60ddfaa1522ee66abe65e5bcc2ced2b435cc84b60f7c23f7d4c22b1c0bc899a582350cf0e1c7ce46191e3747b2b74b4d98d4e2f58b86e71055fc2e2744b1a30'

development:
  <<: *default
  secret_key_base: '4b4e7c87083ef76fa7f88586cd930168ae97c1c59f94510abd7ac017bfb371a865a8c0c44a79d5852c4c709dce19fb461c663bd0bb50558116c0b4264ecec20a'

test:
  <<: *default
  secret_key_base: '4c1676d86f190a25400b4f43c45e9c1aa3d6b882f50e708c167e13a77e56f1ff0868cff7eb1e8dc2c4c8bd8b90dcf242357470b6ad53815edbd02e51fcaa13bf'

production:
  <<: *default
  secret_key_base: <%= ENV['PROD_SECRET'] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  twitter_access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  twitter_access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
